// Textes de l'interface en allemand (traduction de fr.ts, même forme).

import type { Lang } from '@pastille/shared';
import type { Texts } from './fr.ts';
import { clock, daysAgo, hhmm, isMac, isoDay, longDate, minutesAgo, pluralFor, shortDate } from './util.ts';

const plural = pluralFor('de');

function day(iso: string) {
  const days = daysAgo(iso);
  if (days === 0) return 'heute';
  if (days === 1) return 'gestern';
  return shortDate('de', iso);
}

function since(iso: string) {
  const min = minutesAgo(iso);
  if (min < 1) return 'gerade eben';
  if (min < 60) return `seit ${min} Min.`;
  if (min < 24 * 60) return `seit ${Math.floor(min / 60)} Std.`;
  return daysAgo(iso) === 1 ? 'seit gestern' : `seit dem ${day(iso)}`;
}

const sketchOf = (i: number, n: number) => `Skizze ${i} zu #${n}`;
const inspirationOf = (i: number, n: number) => `Inspiration ${i} zu #${n}`;
const inspirationNote = 'Screenshot einer anderen Website, Vorlage für das gewünschte Ergebnis (nicht der zu ändernde Screen)';

export const de: Texts = {

  lang: 'de' as Lang,
  locale: 'de-DE',
  plural,
  day,
  since,
  points: (n: number) => plural(n, 'Punkt', 'Punkte'),
  screens: (n: number) => plural(n, 'Screen', 'Screens'),
  transcriptions: (n: number) => plural(n, 'Transkription', 'Transkriptionen'),
  reveal: isMac ? 'Im Finder zeigen' : 'Im Explorer anzeigen',

  // Retour visuel du mode vidéo (pastille qui suit la souris)
  videoFeedback: {
    microphone: 'Mikro an',
    point: (n: number) => `Punkt ${n}`,
    general: 'Allgemeine Anmerkung',
    speak: 'Sprich, um diesen Punkt zu behalten',
    ready: 'Klicken, dann sprechen',
  },

  menu: {
    label: 'VibeScreener',
    noSession: 'Keine Session offen',
    noSessionHint: 'Der nächste Screenshot startet eine.',
    tablet: 'Tablet verbunden',
    capture: 'Neuer Screenshot',
    video: 'Video aufnehmen',
    stopVideo: 'Aufnahme beenden',
    editor: 'Editor öffnen',
    exportPdf: 'PDF exportieren',
    newSession: 'Neue Session',
    recents: 'Letzte Sessions',
    allSessions: 'Alle Sessions…',
    reexport: (name: string) => `PDF von ${name} erneut exportieren`,
    pair: 'Tablet koppeln…',
    claudeCode: 'Claude Code verbinden…',
    settings: 'Einstellungen…',
    quit: 'VibeScreener beenden',
    update: (version: string) => `Aktualisieren (Version ${version})`,
    trial: (days: number) => `Kostenlose Testphase: noch ${plural(days, 'Tag', 'Tage')}`,
    buy: 'Kaufen',
    license: { expired: 'Testphase abgelaufen', revoked: 'Lizenz nicht mehr gültig', unverified: 'Lizenzprüfung ausstehend' },
    pending: (n: number) => plural(n, 'laufende Transkription', 'laufende Transkriptionen'),
    errors: (n: number) => plural(n, 'fehlgeschlagene Transkription', 'fehlgeschlagene Transkriptionen'),
  },

  bar: {
    label: 'VibeScreener-Session',
    capture: 'Aufnehmen',
    newCapture: 'Neuer Screenshot',
    editor: 'Editor öffnen',
    exportPdf: 'PDF exportieren',
    hide: 'Leiste ausblenden',
    tablet: 'Tablet',
    exported: { pdf: 'PDF exportiert', markdown: 'Markdown-Ordner exportiert', pptx: 'PowerPoint exportiert' },
    copied: 'PDF in die Zwischenablage kopiert',
  },

  overlay: {
    hints: [
      ['Klick', 'Fenster aufnehmen, Punkt {n} setzen'],
      ['Ziehen', `Bereich, ${isMac ? '⌥' : 'Alt'} zum Zuschneiden`],
      ['⇧ Klick', 'letzter Bereich'],
      ['Esc', 'abbrechen'],
    ] as [string, string][],
    inspirationHints: [
      ['Klick', 'Fenster aufnehmen'],
      ['Ziehen', 'Bereich'],
      ['⇧ Klick', 'letzter Bereich'],
      ['Esc', 'zurück zum Punkt'],
    ] as [string, string][],
    wholeScreen: 'Ganzer Bildschirm',
    zone: 'Bereich',
    crop: 'Zuschneiden',
    screen: (session: string, index: number) => `${session} · Screen ${index}`,
    inspiration: (n: number) => `Inspiration für Punkt #${n}`,
  },

  settings: {
    tabs: { general: 'Allgemein', transcription: 'Transkription', export: 'PDF-Export', devices: 'Geräte', claude: 'Claude Code', license: 'Lizenz' },
    capture: 'Screenshot',
    shortcut: 'Tastenkürzel',
    shortcutAria: (label: string) => `Tastenkürzel ändern, aktuell ${label}`,
    shortcutListening: 'Kombination drücken…',
    shortcutHint: isMac
      ? 'Nicht ⇧⌘3, ⇧⌘4 oder ⇧⌘5 (für macOS reserviert). Klick und drück dann die neue Kombination.'
      : 'Klick und drück dann die neue Kombination.',
    shortcutTaken: 'Dieses Tastenkürzel ist nicht verfügbar – wähl ein anderes.',
    shortcutUnsupported: isMac
      ? 'Nicht unterstützt: ⌘, ⌥, ⇧ oder ⌃ mit einem Buchstaben, einer Ziffer oder F1 bis F12.'
      : 'Nicht unterstützt: Ctrl, Alt oder Shift mit einem Buchstaben, einer Ziffer der oberen Tastenreihe (nicht vom Ziffernblock) oder F1 bis F12.',
    comment: 'Kommentar',
    mode: 'Modus',
    modes: { auto: 'Auto-Diktat', push: 'Push-to-Talk', keyboard: 'Nur Tastatur' },
    modeHints: {
      auto: 'Ein gesetzter Punkt öffnet das Mikro.',
      push: `Halte ${isMac ? '⌥' : 'Alt'} gedrückt, um zum ausgewählten Punkt zu diktieren.`,
      keyboard: 'Kein Mikro: Der Kommentar wird getippt.',
    },
    silence: 'Diktat beenden nach einer Stille von',
    silenceSwitch: 'Stopp bei Stille',
    less: 'Weniger',
    more: 'Mehr',
    seconds: (s: number) => `${s} s`,
    language: 'Diktiersprache',
    languages: { fr: 'Französisch', en: 'Englisch', es: 'Spanisch', de: 'Deutsch', it: 'Italienisch', auto: 'Automatische Erkennung' } as Record<string, string>,
    export: 'Export',
    exportDir: 'Exportordner',
    choose: 'Auswählen…',
    copyPdf: 'PDF nach dem Export in die Zwischenablage kopieren',
    app: 'VibeScreener',
    uiLanguage: 'Sprache der Oberfläche',
    uiLanguageAuto: 'Automatisch (Systemsprache)',
    openAtLogin: `VibeScreener beim Start ${isMac ? 'des Macs' : 'des Computers'} öffnen`,
    floatingBar: 'Schwebende Leiste während einer Session',
    floatingBarHint: 'Punktezähler, Screenshot und Export – immer griffbereit.',
    engine: 'Engine',
    engines: { local: 'Whisper lokal', api: 'API mit Schlüssel' },
    engineHints: {
      local: 'Offline: Das Audio verlässt diesen Computer nicht.',
      api: 'Fallback: Das Audio geht an den gewählten Dienst.',
    },
    model: 'Whisper large-v3-turbo',
    modelDetail: 'Quantisiert q5_0 · 547 MB',
    modelState: { ready: 'Bereit', loading: 'Lädt…', missing: 'Nicht heruntergeladen', error: 'Fehler' },
    download: 'Herunterladen',
    apiUrl: 'API-Adresse (OpenAI-kompatibel)',
    apiModel: 'Modell',
    apiKey: 'Schlüssel',
    apiKeySaved: 'gespeichert',
    save: 'Speichern',
    glossary: 'Glossar',
    glossaryHint: 'Begriffe, die sicher erkannt werden sollen (Komponentennamen, Projektjargon).',
    context: 'Projektkontext',
    contextHint: 'Steht am Anfang der Exporte und des Reviews, das Claude Code liest. Gilt für die offene Session und alle folgenden.',
    contextPlaceholder: 'Projekt, Stack, getestete Seite',
    instructions: 'Anweisungen an die KI',
    instructionsHint: 'Am Anfang von PDF, Markdown und dem Review, das Claude Code liest. {N} wird durch die Anzahl der Rückmeldungen ersetzt.',
    claudeCode: 'Claude Code',
    claudeCodeCommand: 'Zum Verbinden führ diesen Befehl einmal im Terminal aus:',
    claudeCodeHint:
      'Claude Code liest dann deine Reviews (Sessions, Rückmeldungen, annotierte Screenshots), solange VibeScreener läuft. Sag zum Beispiel: „Setz das VibeScreener-Review um.“',
    claudeCodeOff: 'Server für Claude Code nicht gestartet.',
    claudeCodeSeen: (iso: string) =>
      `Zuletzt verbunden: ${day(iso)}, ${clock('de', iso)}`,
    claudeCodeNever: 'Noch nicht verbunden',
    copy: 'Kopieren',
    copied: 'Kopiert',
    tablet: 'Tablet',
    tabletPaired: 'Tablet gekoppelt',
    tabletNone: 'Kein Tablet gekoppelt',
    tabletConnected: 'Verbunden',
    tabletOffline: 'Offline',
    tabletHint: 'Ein Tablet zeichnet Skizzen zum ausgewählten Punkt. Die Verbindung ist Ende-zu-Ende-verschlüsselt.',
    showQr: 'QR-Code zeigen',
    pair: 'Koppeln…',
    revoke: 'Entkoppeln',
    license: 'Lizenz',
    licenseStates: {
      trial: (days: number) => `Kostenlose Testphase: noch ${plural(days, 'Tag', 'Tage')}`,
      expired: () => 'Testphase abgelaufen',
      licensed: () => 'Lizenz aktiv',
      revoked: () => 'Lizenz nicht mehr gültig',
      unverified: () => 'Lizenzprüfung ausstehend',
    },
    licenseDetails: {
      trial: 'Alle Funktionen, ohne Kreditkarte.',
      expired: 'Kauf eine Lizenz, um wieder Screenshots aufzunehmen.',
      licensed: 'Danke, dass du VibeScreener unterstützt!',
      revoked: 'Abo beendet oder Kauf erstattet.',
      unverified: 'Polar antwortet seit 30 Tagen nicht – verbinde dich mit dem Internet.',
    },
    buy: 'Kaufen',
    portal: 'Meinen Kauf verwalten',
    licenseKey: 'Lizenzschlüssel',
    licenseKeyHint: 'Du findest ihn in der E-Mail nach dem Kauf.',
    activate: 'Aktivieren',
    activating: 'Aktivierung…',
    activated: `Lizenz auf ${isMac ? 'diesem Mac' : 'diesem Computer'} aktiviert.`,
    licenseHint:
      'Ohne Lizenz sind nach der Testphase neue Screenshots gesperrt. Deine Sessions, Exporte und Claude Code bleiben verfügbar.',
  },

  welcome: {
    step: (n: number) => `Schritt ${n} von 3`,
    continue: 'Weiter',
    back: 'Zurück',
    finish: 'Fertig',
    permissions: {
      title: isMac ? 'Zwei Berechtigungen zum Start' : 'Eine Berechtigung zum Start',
      intro: 'VibeScreener nimmt das Fenster auf, das du prüfst, und hört deine Kommentare. Bilder und Audio bleiben auf diesem Computer.',
      screen: 'Bildschirmaufnahme',
      screenWhy: 'Um das zu prüfende Fenster in voller Auflösung aufzunehmen.',
      mic: 'Mikrofon',
      micWhy: 'Um zu jedem gesetzten Punkt einen Kommentar zu diktieren.',
      granted: 'Erlaubt',
      allow: 'Erlauben',
      relaunch: 'macOS verlangt nach der Bildschirmfreigabe evtl. einen Neustart von VibeScreener – dieser Assistent öffnet sich dann wieder.',
      keyboardOnly: 'Kein Mikro? Nur Tastatur nutzen',
      keyboardChosen: 'Nur Tastatur: Das Mikro wird nicht verwendet.',
    },
    model: {
      title: 'Das Diktiermodell wird geladen',
      titleReady: 'Das Diktiermodell ist bereit',
      intro: 'Whisper transkribiert offline auf diesem Computer. Der Download ist nur einmal nötig.',
      name: 'Whisper large-v3-turbo',
      detail: 'Quantisiert q5_0 · 547 MB · gut auf Deutsch',
      progress: (percent: number) => `${Math.round((percent * 547) / 100)} MB von 547 MB`,
      ready: 'Bereit',
      retry: 'Erneut versuchen',
      note: 'Du kannst gleich weitermachen. Tippen geht schon; das Diktat startet von selbst, sobald der Download fertig ist.',
      useApi: 'Stattdessen eine API mit Schlüssel nutzen',
      apiChosen: 'Transkription per API: Den Schlüssel legst du in den Einstellungen fest.',
    },
    shortcut: {
      title: 'Probier das Tastenkürzel aus',
      intro: (keys: number) =>
        `Öffne die zu prüfende Seite und drück dann ${keys > 2 ? 'diese drei Tasten' : 'dieses Tastenkürzel'}. Danach bleibt VibeScreener ${isMac ? 'im Dock und in der Menüleiste' : 'im Infobereich der Taskleiste'}.`,
      waiting: 'Warte auf Tastendruck…',
      steps: [
        ['Tastenkürzel', 'Der Bildschirm friert ein.'],
        ['Klick aufs Element', 'Der Punkt wird gesetzt, das Mikro geht an.'],
        ['Sprich', 'Dann klick aufs nächste Element.'],
      ] as [string, string][],
      openAtLogin: `VibeScreener beim Start ${isMac ? 'des Macs' : 'des Computers'} öffnen`,
      other: 'Anderes Tastenkürzel wählen',
    },
    trial: (days: number) => `Kostenlose Testphase: noch ${plural(days, 'Tag', 'Tage')}, alle Funktionen, ohne Kreditkarte.`,
  },

  pairing: {
    title: 'Scanne diesen Code mit dem Tablet',
    qr: 'QR-Code zum Koppeln',
    waiting: 'Warte auf das Tablet…',
    connected: 'Tablet verbunden',
    steps: [
      'Öffne die Kamera des Tablets und richte sie auf den Code.',
      'Tippe auf den Link, dann auf Teilen › Zum Home-Bildschirm, um die App zu installieren.',
      'Fertig: Das Tablet verbindet sich bei jedem Öffnen von selbst.',
    ],
    secure: 'Ende-zu-Ende-verschlüsselt. Der Schlüssel steckt im Code und geht nie über den Server – zeig ihn nur deinem Tablet.',
    devices: 'Gekoppelte Geräte',
    tablet: 'Tablet',
    online: 'Verbunden',
    revoke: 'Entkoppeln',
    revokeHint: 'Ein neuer Code wird erstellt: Das Tablet muss ihn erneut scannen.',
  },

  editor: {
    rename: 'Session umbenennen',
    sessions: 'Sessions',
    allSessions: 'Alle Sessions',
    noSessions: 'Keine gespeicherten Sessions.',
    sessionOpen: 'offen',
    openSession: (name: string) => `${name} öffnen`,
    exportSession: (name: string) => `PDF von ${name} exportieren`,
    trashSession: (name: string) => `${name} in den Papierkorb legen`,
    close: 'Schließen',
    tablet: 'Tablet verbunden',
    export: 'Exportieren',
    formats: { pdf: 'PDF für die KI', markdown: 'Markdown-Ordner + Bilder', pptx: 'PowerPoint (Präsentation)' },
    exporting: { pdf: 'PDF-Export…', markdown: 'Markdown-Export…', pptx: 'PowerPoint-Export…' },
    exported: (path: string) => `Exportiert: ${path}`,
    stageHints: [
      ['Klick', 'Punkt'],
      ['Ziehen', 'Bereich'],
      ['⇧ Ziehen', 'Pfeil'],
    ] as [string, string][],
    zoomOut: 'Verkleinern',
    zoomIn: 'Vergrößern',
    screenTitle: (index: number, points: number) => `Screen ${index} · ${plural(points, 'Punkt', 'Punkte')}`,
    previous: 'Vorheriger Screenshot',
    next: 'Nächster Screenshot',
    noPoints: 'Klick auf den Screenshot, um einen Punkt zu setzen.',
    undoAll: (mod: string) => `${mod}Z macht alles rückgängig, auch Löschen`,
    panel: 'Punkte und Anmerkungen',
    pointsTab: 'Punkte',
    notes: 'Allgemeine Anmerkungen',
    note: 'Anmerkung',
    addNote: 'Anmerkung hinzufügen',
    notesHint: 'ohne bestimmten Punkt',
    notePlaceholder: 'Deine Anmerkung…',
    dictateNote: 'Weiter diktieren',
    dictateMore: (mod: string) => `Weiter diktieren (${mod}M)`,
    keyDictate: (mod: string) => [`${mod}M`, 'weiter diktieren'] as [string, string],
    stopDictation: 'Diktat beenden',
    deleteNote: 'Anmerkung löschen',
    kinds: { point: 'Punkt', zone: 'Bereich', arrow: 'Pfeil' },
    dictated: 'Diktiert',
    typed: 'Getippt',
    transcribing: 'wird transkribiert…',
    transcriptionError: 'Transkription fehlgeschlagen',
    retry: 'Erneut versuchen',
    recording: 'Diktat läuft',
    tabletDraws: 'das Tablet zeichnet für diesen Punkt',
    sketches: (n: number) => `${plural(n, 'Skizze', 'Skizzen')} · Tablet`,
    zoomSketch: 'Skizze vergrößern',
    deleteSketch: 'Skizze löschen',
    inspiration: 'Inspiration',
    inspirationTitle: (shortcut: string, mod: string) =>
      `Beispiel einer anderen Website anhängen: Der Editor verschwindet, öffne die Vorlagenseite und drück ${shortcut}. Oder füge ein Bild ein (${mod}V).`,
    inspirationHint: (shortcut: string, mod: string) => `dann ${shortcut} auf der Vorlagenseite oder ${mod}V`,
    inspirations: (n: number) => plural(n, 'Inspiration', 'Inspirationen'),
    zoomInspiration: 'Inspiration vergrößern',
    deleteInspiration: 'Inspiration löschen',
    imageNeedsPoint: 'Wähl zuerst einen Punkt aus – das Bild wird zu seiner Inspiration.',
    unreadableImage: 'Bild nicht lesbar.',
    deletePoint: 'Punkt löschen',
    noComment: 'Ohne Kommentar',
    bubbleLabel: (n: number) => `Kommentar zu Punkt ${n}`,
    placeholderRecording: 'Sprich oder tippe…',
    placeholder: 'Dein Kommentar…',
    sketchHint: 'Skizze: Zeichne auf dem Tablet',
    keys: [
      ['Enter', 'bestätigen'],
      ['Esc', 'abbrechen'],
    ] as [string, string][],
    keyToType: ['eine Taste', 'zur Tastatur wechseln'] as [string, string],
    thumb: (index: number, first?: number, last?: number) =>
      `Screen ${index} · ${first === undefined ? 'kein Punkt' : first === last ? `#${first}` : `#${first}–${last}`}`,
    thumbLabel: (index: number, points: number, current: boolean) =>
      `Screen ${index}, ${plural(points, 'Punkt', 'Punkte')}${current ? ', angezeigt' : ''}`,
    captures: 'Screenshots der Session',
    deleteScreen: (index: number) => `Screen ${index} und seine Punkte löschen`,
    screenDeleted: (index: number, mod: string) => `Screen ${index} gelöscht · Rückgängig mit ${mod}Z`,
    newCapture: 'Neuer Screenshot',
    emptyTitle: 'Noch keine Screenshots',
    emptyBefore: 'Drück auf dem zu prüfenden Bildschirm',
    emptyAfter: 'und klick dann auf das zu korrigierende Element.',
    micError: (err: unknown) => `Mikro nicht verfügbar: ${err}`,
    zoomedImage: 'Vergrößertes Bild',
  },

  main: {
    windows: { pairing: 'Tablet koppeln', settings: 'VibeScreener-Einstellungen', welcome: 'Willkommen bei VibeScreener' },
    newReview: 'Neues Review',
    cancel: 'Abbrechen',
    nothingToExport: 'Nichts zu exportieren: keine Screenshots.',
    untranscribed: 'Einige Diktate sind noch nicht transkribiert.',
    untranscribedPending: (list: string) => `In Arbeit: ${list}`,
    untranscribedError: (list: string) => `Fehlgeschlagen: ${list}`,
    exportAnyway: 'Trotzdem exportieren',
    exportCancelled: 'Export abgebrochen.',
    note: (n: number) => `Anmerkung ${n}`,
    update: (version: string) => `VibeScreener auf Version ${version} aktualisieren?`,
    updateDetail: 'Die App schließt sich, wird aktualisiert und öffnet sich wieder (etwa eine Minute). Sessions und Einstellungen bleiben erhalten.',
    updateDetailMac: 'Da die App nicht von Apple signiert ist, fragt macOS erneut nach der Erlaubnis für Bildschirmaufnahme, Mikrofon und Bedienungshilfen (Videomodus).',
    updateNow: 'Aktualisieren',
    later: 'Später',
    shortcutTaken: (label: string) => `${label} ist bereits von einer anderen App belegt.`,
    shortcutTakenAtStart: (label: string) => `Das Tastenkürzel ${label} ist bereits von einer anderen App belegt.`,
    shortcutTakenDetail: 'Wähl in den Einstellungen ein anderes. Screenshots gehen weiterhin über das VibeScreener-Symbol.',
    trash: (name: string) => `Session „${name}“ in den Papierkorb legen?`,
    trashDetail: 'Ihre Screenshots und Kommentare wandern mit. Du kannst sie aus dem Papierkorb wiederherstellen.',
    trashConfirm: 'In den Papierkorb legen',
    trashFailed: (err: string) => `Verschieben in den Papierkorb fehlgeschlagen: ${err}`,
    mcpPortTaken: (port: number) => `Port ${port} ist bereits belegt (eine weitere VibeScreener-Instanz?): Claude Code kann sich nicht verbinden.`,
    mcpUnavailable: (err: string) => `Server für Claude Code nicht verfügbar: ${err}`,
    captureDenied:
      'Screenshot nicht möglich: Erlaube die Bildschirmaufnahme (Systemeinstellungen > Datenschutz & Sicherheit) und starte VibeScreener neu.',
    captureFailed: 'Screenshot nicht möglich: Der Bildschirm konnte nicht gelesen werden.',
    video: {
      clicks: 'Der Videomodus muss deine Klicks sehen.',
      clicksDetail: (shortcut: string) =>
        `Erlaube VibeScreener unter Systemeinstellungen > Datenschutz & Sicherheit > Bedienungshilfen und starte die Aufnahme erneut (${shortcut}).`,
      openSettings: 'Einstellungen öffnen',
      empty: 'Kein Punkt aufgenommen.',
      emptyDetail: 'Klick während der Aufnahme auf ein Element und sprich dann: Jeder Klick mit gesprochenem Text wird ein Punkt.',
      shortcutTaken: (label: string) => `Das Kürzel ${label} für den Videomodus wird schon von einer anderen App verwendet.`,
      shortcutTakenDetail: 'Der Videomodus bleibt über das VibeScreener-Symbol verfügbar.',
      denied: 'Aufnahme nicht möglich: Erlaube die Bildschirmaufnahme (Systemeinstellungen > Datenschutz & Sicherheit) und starte VibeScreener neu.',
      unreadable: 'Aufnahme nicht möglich: Der Bildschirm konnte nicht gelesen werden.',
      noResponse: 'Bildschirme oder Mikrofon antworten nicht.',
      failed: (err: string) => `Aufnahme nicht möglich: ${err}`,
    },
    tray: {
      session: (name: string, points: number) => `VibeScreener — ${name} (${plural(points, 'Punkt', 'Punkte')})`,
      recording: 'Diktat läuft',
      pending: (n: number) => plural(n, 'laufende Transkription', 'laufende Transkriptionen'),
      errors: (n: number) => plural(n, 'fehlgeschlagene Transkription', 'fehlgeschlagene Transkriptionen'),
      tablet: 'Tablet verbunden',
    },
    appMenu: {
      about: 'Über VibeScreener',
      settings: 'Einstellungen…',
      hide: 'VibeScreener ausblenden',
      quit: 'VibeScreener beenden',
      edit: 'Bearbeiten',
      undo: 'Widerrufen',
      redo: 'Wiederholen',
      cut: 'Ausschneiden',
      copy: 'Kopieren',
      paste: 'Einsetzen',
      selectAll: 'Alles auswählen',
      window: 'Fenster',
      minimize: 'Im Dock ablegen',
      close: 'Schließen',
    },
    license: {
      emptyKey: 'Füge den Schlüssel aus der E-Mail ein.',
      notForSale: 'Lizenzen sind noch nicht erhältlich – versuch es bald wieder.',
      offline: 'Polar ist nicht erreichbar – prüf deine Internetverbindung.',
      unknownKey: 'Unbekannter Schlüssel – prüf ihn in der E-Mail nach dem Kauf.',
      refused: `Schlüssel abgelehnt: bereits auf der Höchstzahl an ${isMac ? 'Macs' : 'Computern'} aktiviert, widerrufen oder abgelaufen.`,
      polarError: (status: number) => `Polar antwortet nicht korrekt (Fehler ${status}) – versuch es später erneut.`,
    },
    whisper: {
      modelMissing: 'Whisper-Modell fehlt – lade es in den Einstellungen herunter.',
      binMissing: 'whisper-server nicht gefunden.',
      unavailable: (status: string) => `Transkription nicht verfügbar: ${status}`,
      download: (status: number, url: string) => `Download fehlgeschlagen (${status}): ${url}`,
      stopped: (stderr: string) => `whisper-server wurde beim Start beendet:\n${stderr}`,
      timeout: 'whisper-server antwortet nach 120 s nicht',
    },
  },

  exports: {
    colon: ': ',
    date: (iso: string) => longDate('de-DE', iso),
    reviewFile: 'review',
    partFile: (i: number, n: number) => `teil-${i}-von-${n}`,
    part: (i: number, n: number) => `Teil ${i}/${n}`,
    partScreens: (first: number, last: number) => `dieser Teil: Screens ${first} bis ${last}`,
    screen: (n: number) => `Screen ${n}`,
    position: 'Position',
    point: (x: number, y: number, size: string) => `x ${x}, y ${y} ${size}`,
    zone: (x: number, y: number, w: number, h: number, size: string) => `Bereich x ${x}, y ${y}, ${w} × ${h} ${size}`,
    arrow: (x1: number, y1: number, x2: number, y2: number, size: string) => `Pfeil von (${x1}, ${y1}) nach (${x2}, ${y2}) ${size}`,
    on: (w: number, h: number) => `auf ${w} × ${h}`,
    yes: 'ja',
    no: 'nein',
    context: 'Kontext',
    instructions: 'Anweisungen',
    notes: 'Allgemeine Anmerkungen',
    summary: 'Übersicht',
    columns: { screen: 'Screen', comment: 'Kommentar', sketch: 'Skizze', inspiration: 'Inspiration' },
    noComment: '(ohne Kommentar)',
    zoomOn: (n: number) => `Zoom auf #${n}`,
    sketchOf,
    inspiration: 'Inspiration',
    inspirationOf,
    inspirationNote,
  },

  mcp: {
    instructions: `VibeScreener speichert UI-Reviews: Screenshots, auf denen jede Rückmeldung ein nummerierter Punkt (#1 bis #N) mit einem Kommentar ist, oft diktiert, manchmal mit einer Skizze oder einer Inspiration (Screenshot einer anderen Website, der das gewünschte Ergebnis zeigt, nicht der zu ändernde Screen).
Um ein Review im Code umzusetzen: Ohne Angabe des Nutzers die in VibeScreener offene Session nehmen (Standard), sonst sie mit lister_sessions auswählen. lire_revue liefert alle Rückmeldungen; voir_ecran zeigt Screen für Screen den annotierten Screenshot, einen Zoom um jeden Punkt, die Skizzen und die Inspirationen. Jeden Screen ansehen, bevor der Code geändert wird. Ist eine Rückmeldung mehrdeutig, eine Frage stellen statt zu raten.`,
    sessionParam: 'Id der Session (siehe lister_sessions). Standard: die in VibeScreener offene Session, sonst die neueste.',
    listTool: 'Listet die letzten Review-Sessions auf (Name, Datum, Anzahl der Punkte, Id), die neueste zuerst.',
    reviewTool:
      'Alle Rückmeldungen einer Session als Text: Kontext, Anweisungen, dann jeder Punkt (Nummer, Screen, Kommentar, Position, Skizzen, Inspirationen). Die Bilder liefert voir_ecran.',
    screenTool:
      'Ein Screen einer Session: der Screenshot mit seinen nummerierten Punkten, dann zu jedem Punkt sein Kommentar, ein Zoom um das betroffene Element, seine Skizzen und seine Inspirationen (Screenshots anderer Websites, Vorlagen für das gewünschte Ergebnis).',
    screenParam: 'Nummer des Screens, von 1 bis zur Anzahl der Screens, die lire_revue angibt.',
    noSession: 'Keine Session: zuerst mit VibeScreener einen Screenshot aufnehmen.',
    notFound: (id: string) => `Session „${id}“ nicht gefunden.`,
    notFoundList: (id: string) => `Session „${id}“ nicht gefunden: siehe lister_sessions.`,
    noSessions: 'Noch keine Sessions.',
    sessions: 'Sessions, die neueste zuerst:',
    sessionLine: (name: string, date: string, points: number, id: string, open: boolean) =>
      `- ${name} · geändert am ${date} · ${plural(points, 'Punkt', 'Punkte')} · id: ${id}${open ? ' (offen in VibeScreener)' : ''}`,
    untranscribed: (list: string) => `Achtung: Diktat für ${list} noch nicht transkribiert; der Kommentar kann unvollständig sein.`,
    noPoints: '(keine Punkte)',
    sketches: (n: number) => plural(n, 'Skizze', 'Skizzen'),
    inspirations: (n: number) => plural(n, 'Inspiration', 'Inspirationen'),
    seeScreens: (n: number) =>
      `Für den annotierten Screenshot, den Zoom jedes Punkts, die Skizzen und die Inspirationen: voir_ecran mit ecran von 1 bis ${n}.`,
    noScreen: (screen: string, name: string, screens: number) =>
      `Screen ${screen} existiert nicht: Die Session „${name}“ hat ${plural(screens, 'Screen', 'Screens')}.`,
    zoom: 'Zoom auf das betroffene Element:',
    error: (err: string) => `VibeScreener-Fehler: ${err}`,
  },

  glossary:
    'UI-Feedback: Schaltfläche, border-radius von 8 px, padding, margin, header, footer, ' +
    'sidebar, navbar, Modal, dropdown, hover, focus, flexbox, grid, z-index, Deckkraft.',

  instructions: `Dieses Dokument listet {N} Rückmeldungen zu einer Oberfläche auf, nummeriert von #1 bis #{N}.
Jede Rückmeldung zeigt auf ein Element in einem Screenshot: Die nummerierte Markierung und der
Ausschnitt zeigen das betroffene Element, ein Rechteck markiert einen Bereich, ein Pfeil eine Verschiebung.
Setze jede Rückmeldung im Code um. Ist eine Rückmeldung mehrdeutig, stell eine Frage,
statt zu raten. Liste am Ende auf, welche Nummern du umgesetzt hast und welche nicht.`,

  sessionName: (d: Date) => `Review ${isoDay(d)} ${hhmm(d, ':')}`,
};
