// Textes de l'interface en espagnol (Espagne) (traduction de fr.ts, même forme).

import type { Lang } from '@pastille/shared';
import type { Texts } from './fr.ts';
import { clock, daysAgo, hhmm, isMac, isoDay, longDate, minutesAgo, pluralFor, shortDate } from './util.ts';

const plural = pluralFor('es');

function day(iso: string) {
  const days = daysAgo(iso);
  if (days === 0) return 'hoy';
  if (days === 1) return 'ayer';
  return shortDate('es', iso);
}

function since(iso: string) {
  const min = minutesAgo(iso);
  if (min < 1) return 'desde hace un momento';
  if (min < 60) return `desde hace ${min} min`;
  if (min < 24 * 60) return `desde hace ${Math.floor(min / 60)} h`;
  return daysAgo(iso) === 1 ? 'desde ayer' : `desde el ${day(iso)}`;
}

const sketchOf = (i: number, n: number) => `Boceto ${i} de #${n}`;
const inspirationOf = (i: number, n: number) => `Inspiración ${i} de #${n}`;
const inspirationNote = 'captura de otra web, modelo del resultado deseado (no es la pantalla que hay que modificar)';

export const es: Texts = {

  lang: 'es' as Lang,
  locale: 'es-ES',
  plural,
  day,
  since,
  points: (n: number) => plural(n, 'punto', 'puntos'),
  screens: (n: number) => plural(n, 'pantalla', 'pantallas'),
  transcriptions: (n: number) => plural(n, 'transcripción', 'transcripciones'),
  reveal: isMac ? 'Mostrar en el Finder' : 'Mostrar en el Explorador de archivos',

  // Retour visuel du mode vidéo (pastille qui suit la souris)
  videoFeedback: {
    microphone: 'Micro abierto',
    point: (n: number) => `Punto ${n}`,
    general: 'Nota general',
    speak: 'Habla para conservar este punto',
    key: isMac ? '⌘' : 'Ctrl',
    click: 'clic',
    placePoint: 'añadir un punto',
    navigate: 'navegar',
    stop: 'Detener',
    drawing: 'Dibujar en la tableta',
    drawingReady: 'El dibujo se adjunta a este punto',
    writePlaceholder: 'Escribe un comentario…',
    writeHint: 'Intro: guardar · Esc: cancelar',
    gestures: `${isMac ? '⌘' : 'Ctrl'} + arrastrar: marco · + ⇧: flecha · + ${isMac ? '⌥' : 'Alt'}: recortar`,
    chooseInspiration: 'Elige una inspiración',
    inspirationHint: (shortcut: string) => `Abre la página de referencia y pulsa ${shortcut}`,
    captureInspiration: 'Capturar inspiración',
    resume: 'Reanudar la grabación',
    pointUnavailable: `No se pudo guardar el punto. Vuelve a hacer ${isMac ? '⌘' : 'Ctrl'} + clic en un elemento.`,
  },

  menu: {
    label: 'VibeScreener',
    noSession: 'Ninguna sesión abierta',
    noSessionHint: 'La próxima captura abrirá una.',
    tablet: 'Tableta conectada',
    capture: 'Nueva captura',
    video: 'Grabar un vídeo',
    stopVideo: 'Detener la grabación',
    openDocument: 'Comentar un documento…',
    editor: 'Abrir el editor',
    exportPdf: 'Exportar el PDF',
    newSession: 'Nueva sesión',
    recents: 'Sesiones recientes',
    allSessions: 'Todas las sesiones…',
    reexport: (name: string) => `Reexportar el PDF de ${name}`,
    pair: 'Vincular una tableta…',
    claudeCode: 'Conectar Claude Code…',
    settings: 'Ajustes…',
    quit: 'Salir de VibeScreener',
    update: (version: string) => `Actualizar (versión ${version})`,
    trial: (days: number) => `Prueba gratuita: ${plural(days, 'día', 'días')}`,
    buy: 'Comprar',
    license: { expired: 'Prueba terminada', revoked: 'Licencia ya no válida', unverified: 'Licencia por verificar' },
    pending: (n: number) => `${plural(n, 'transcripción', 'transcripciones')} en curso`,
    errors: (n: number) => `${plural(n, 'transcripción', 'transcripciones')} con error`,
  },

  bar: {
    label: 'Sesión de VibeScreener',
    capture: 'Capturar',
    newCapture: 'Nueva captura',
    editor: 'Abrir el editor',
    exportPdf: 'Exportar el PDF',
    hide: 'Ocultar la barra',
    tablet: 'Tableta',
    exported: { pdf: 'PDF exportado', markdown: 'Carpeta Markdown exportada', pptx: 'PowerPoint exportado', document: 'Copia comentada exportada' },
    copied: 'PDF copiado al portapapeles',
  },

  overlay: {
    hints: [
      ['Clic', 'captura la ventana y coloca el punto {n}'],
      ['Arrastrar', `zona, ${isMac ? '⌥' : 'Alt'} para recortar`],
      ['⇧ Clic', 'última zona'],
      ['Esc', 'cancelar'],
    ] as [string, string][],
    inspirationHints: [
      ['Clic', 'captura la ventana'],
      ['Arrastrar', 'zona'],
      ['⇧ Clic', 'última zona'],
      ['Esc', 'volver al punto'],
    ] as [string, string][],
    wholeScreen: 'Pantalla completa',
    zone: 'Zona',
    crop: 'Recorte',
    screen: (session: string, index: number) => `${session} · pantalla ${index}`,
    inspiration: (n: number) => `Inspiración del punto #${n}`,
  },

  settings: {
    tabs: { general: 'General', permissions: 'Permisos', transcription: 'Transcripción', export: 'Exportar PDF', devices: 'Dispositivos', claude: 'Claude Code', license: 'Licencia' },
    permissions: 'Permisos del sistema',
    permissionsHint: isMac
      ? 'Como VibeScreener no está firmada por Apple, macOS los olvida en cada actualización: vuelve a darlos aquí. La accesibilidad solo la usa el modo vídeo.'
      : 'El micrófono se configura en Configuración › Privacidad y seguridad › Micrófono.',
    notGranted: 'No permitido',
    capture: 'Captura',
    shortcut: 'Atajo de captura',
    shortcutAria: (label: string) => `Cambiar el atajo, ahora ${label}`,
    shortcutListening: 'Pulsa la combinación…',
    shortcutHint: isMac
      ? 'Evita ⇧⌘3, ⇧⌘4 y ⇧⌘5, reservados por macOS. Haz clic y pulsa la nueva combinación.'
      : 'Haz clic y pulsa la nueva combinación.',
    shortcutTaken: 'Este atajo no está disponible: elige otro.',
    shortcutUnsupported: isMac
      ? 'Combinación no admitida: ⌘, ⌥, ⇧ o ⌃ con una letra, un número o de F1 a F12.'
      : 'Combinación no admitida: Ctrl, Alt o Shift con una letra, un número de la fila superior (no del teclado numérico) o de F1 a F12.',
    comment: 'Comentario',
    mode: 'Modo',
    modes: { auto: 'Dictado auto', push: 'Pulsar para hablar', keyboard: 'Solo teclado' },
    modeHints: {
      auto: 'Al colocar un punto se abre el micro.',
      push: `Mantén pulsado ${isMac ? '⌥' : 'Alt'} para dictar en el punto seleccionado.`,
      keyboard: 'Sin micro: el comentario se escribe.',
    },
    silence: 'Detener el dictado tras un silencio de',
    silenceSwitch: 'Parada por silencio',
    less: 'Menos',
    more: 'Más',
    seconds: (s: number) => `${s} s`,
    language: 'Idioma del dictado',
    languages: { fr: 'Francés', en: 'Inglés', es: 'Español', de: 'Alemán', it: 'Italiano', auto: 'Detección automática' } as Record<string, string>,
    export: 'Exportación',
    exportDir: 'Carpeta de exportación',
    choose: 'Elegir…',
    copyPdf: 'Copiar el PDF al portapapeles tras exportarlo',
    app: 'VibeScreener',
    uiLanguage: 'Idioma de la interfaz',
    uiLanguageAuto: 'Automático (idioma del sistema)',
    openAtLogin: `Abrir VibeScreener al iniciar ${isMac ? 'el Mac' : 'el ordenador'}`,
    floatingBar: 'Barra flotante durante una sesión',
    floatingBarHint: 'Contador de puntos, captura y exportación, siempre a mano.',
    engine: 'Motor',
    engines: { local: 'Whisper local', api: 'API con clave' },
    engineHints: {
      local: 'Sin conexión: el audio no sale de este ordenador.',
      api: 'Alternativa: el audio se envía al servicio elegido.',
    },
    model: 'Whisper large-v3-turbo',
    modelDetail: 'Cuantizado q5_0 · 547 MB',
    modelState: { ready: 'Listo', loading: 'Cargando…', missing: 'No descargado', error: 'Error' },
    download: 'Descargar',
    apiUrl: 'Dirección de la API (compatible con OpenAI)',
    apiModel: 'Modelo',
    apiKey: 'Clave',
    apiKeySaved: 'guardada',
    save: 'Guardar',
    glossary: 'Glosario',
    glossaryHint: 'Vocabulario que debe reconocerse bien (nombres de componentes, jerga del proyecto).',
    context: 'Contexto del proyecto',
    contextHint: 'Al principio de las exportaciones y de la revisión que lee Claude Code. Se aplica a la sesión abierta y a las siguientes.',
    contextPlaceholder: 'Proyecto, stack, página probada',
    instructions: 'Instrucciones para la IA',
    instructionsHint: 'Al principio del PDF, del Markdown y de la revisión que lee Claude Code. {N} se sustituye por el número de observaciones.',
    claudeCode: 'Claude Code',
    claudeCodeCommand: 'Para conectarlo, ejecuta una vez este comando en un terminal:',
    claudeCodeHint:
      'Claude Code podrá leer tus revisiones (sesiones, observaciones, capturas anotadas) mientras VibeScreener esté abierta. Pídele, por ejemplo, «aplica la revisión de VibeScreener».',
    claudeCodeOff: 'Servidor para Claude Code no iniciado.',
    claudeCodeSeen: (iso: string) =>
      `Conectado ${daysAgo(iso) > 1 ? 'el ' : ''}${day(iso)} a las ${clock('es', iso)}`,
    claudeCodeNever: 'Aún no conectado',
    copy: 'Copiar',
    copied: 'Copiado',
    tablet: 'Tableta',
    tabletPaired: 'Tableta vinculada',
    tabletNone: 'Ninguna tableta vinculada',
    tabletConnected: 'Conectada',
    tabletOffline: 'Sin conexión',
    tabletHint: 'Una tableta dibuja los bocetos del punto seleccionado. La conexión está cifrada de extremo a extremo.',
    showQr: 'Mostrar el QR',
    pair: 'Vincular…',
    revoke: 'Revocar',
    license: 'Licencia',
    licenseStates: {
      trial: (days: number) => `Prueba gratuita: ${plural(days, 'día restante', 'días restantes')}`,
      expired: () => 'Prueba terminada',
      licensed: () => 'Licencia activa',
      revoked: () => 'Licencia ya no válida',
      unverified: () => 'Licencia por verificar',
    },
    licenseDetails: {
      trial: 'Todas las funciones, sin tarjeta de crédito.',
      expired: 'Compra una licencia para volver a capturar.',
      licensed: '¡Gracias por apoyar a VibeScreener!',
      revoked: 'Suscripción terminada o compra reembolsada.',
      unverified: 'Polar no responde desde hace 30 días: conéctate a Internet.',
    },
    buy: 'Comprar',
    portal: 'Gestionar mi compra',
    licenseKey: 'Clave de licencia',
    licenseKeyHint: 'Aparece en el correo que recibiste tras la compra.',
    activate: 'Activar',
    activating: 'Activando…',
    activated: `Licencia activada en ${isMac ? 'este Mac' : 'este ordenador'}.`,
    licenseHint:
      'Sin licencia, al terminar la prueba, se bloquean las nuevas capturas. Tus sesiones, tus exportaciones y Claude Code siguen disponibles.',
  },

  welcome: {
    step: (n: number) => `Paso ${n} de 3`,
    continue: 'Continuar',
    back: 'Atrás',
    finish: 'Terminar',
    permissions: {
      title: isMac ? 'Dos permisos para empezar' : 'Un permiso para empezar',
      intro: 'VibeScreener captura la ventana que revisas y escucha tus comentarios. Las imágenes y el audio no salen de este ordenador.',
      screen: 'Grabación de pantalla',
      screenWhy: 'Para capturar la ventana que revisas a resolución completa.',
      mic: 'Micrófono',
      micWhy: 'Para dictar un comentario en cada punto que colocas.',
      granted: 'Concedido',
      allow: 'Permitir',
      relaunch: 'macOS puede pedirte que reinicies VibeScreener tras permitir la grabación de pantalla: este asistente se volverá a abrir.',
      keyboardOnly: '¿Sin micro? Usar solo el teclado',
      keyboardChosen: 'Solo teclado: no se usará el micro.',
      accessibility: 'Accesibilidad',
      accessibilityWhy: 'Opcional: para el modo vídeo, que sigue tus clics.',
    },
    model: {
      title: 'Descargando el modelo de dictado',
      titleReady: 'El modelo de dictado está listo',
      intro: 'Whisper transcribe en este ordenador, sin conexión. Esta descarga solo se hace una vez.',
      name: 'Whisper large-v3-turbo',
      detail: 'Cuantizado q5_0 · 547 MB · bueno en español',
      progress: (percent: number) => `${Math.round((percent * 547) / 100)} MB de 547 MB`,
      ready: 'Listo',
      retry: 'Reintentar',
      note: 'Puedes continuar sin esperar. Ya puedes escribir con el teclado; el dictado se activará solo al terminar la descarga.',
      useApi: 'Usar una API con clave',
      apiChosen: 'Transcripción por API: la clave se configura en los ajustes.',
    },
    shortcut: {
      title: 'Prueba el atajo',
      intro: (keys: number) =>
        `Abre la página que quieres revisar y pulsa ${keys > 2 ? 'estas teclas a la vez' : 'este atajo'}. Después, VibeScreener se queda en ${isMac ? 'la barra de menús' : 'el área de notificación'}.`,
      waiting: 'Esperando la pulsación…',
      steps: [
        ['Atajo', 'La pantalla se congela.'],
        ['Clic en el elemento', 'Se coloca el punto y se abre el micro.'],
        ['Habla', 'Luego haz clic en el siguiente elemento.'],
      ] as [string, string][],
      openAtLogin: `Abrir VibeScreener al iniciar ${isMac ? 'el Mac' : 'el ordenador'}`,
      other: 'Elegir otro atajo',
      videoTitle: 'Novedad: el modo vídeo',
      video: (shortcut: string) =>
        `${shortcut} inicia una grabación: navega con clics, y haz ${isMac ? '⌘' : 'Ctrl'} + clic en un elemento y habla para convertirlo en un punto. ${shortcut} o «Detener» la termina.`,
    },
    trial: (days: number) => `Prueba gratuita: ${plural(days, 'día restante', 'días restantes')}, todas las funciones, sin tarjeta de crédito.`,
  },

  pairing: {
    title: 'Escanea este código con la tableta',
    qr: 'Código QR de vinculación',
    waiting: 'Esperando la tableta…',
    connected: 'Tableta conectada',
    steps: [
      'Abre la cámara de la tableta y apunta al código.',
      'Toca el enlace y luego Compartir › Añadir a pantalla de inicio para instalar la app.',
      'Listo: la tableta se volverá a conectar sola cada vez que abras la app.',
    ],
    secure: 'Cifrado de extremo a extremo. La clave va en el código y nunca pasa por el servidor: enséñalo solo a tu tableta.',
    devices: 'Dispositivos vinculados',
    tablet: 'Tableta',
    online: 'Conectada',
    revoke: 'Revocar',
    revokeHint: 'Se crea un código nuevo: tendrás que volver a escanearlo con la tableta.',
  },

  editor: {
    rename: 'Renombrar la sesión',
    sessions: 'Sesiones',
    allSessions: 'Todas las sesiones',
    noSessions: 'No hay sesiones guardadas.',
    sessionOpen: 'abierta',
    openSession: (name: string) => `Abrir ${name}`,
    exportSession: (name: string) => `Exportar el PDF de ${name}`,
    trashSession: (name: string) => `Mover ${name} a la papelera`,
    close: 'Cerrar',
    tablet: 'Tableta conectada',
    export: 'Exportar',
    formats: { pdf: 'PDF para la IA', markdown: 'Carpeta Markdown + imágenes', pptx: 'PowerPoint (presentación)', document: 'Copia comentada del documento' },
    exporting: { pdf: 'Exportando el PDF…', markdown: 'Exportando Markdown…', pptx: 'Exportando PowerPoint…', document: 'Escribiendo la copia comentada…' },
    exported: (path: string) => `Exportado: ${path}`,
    stageHints: [
      ['Clic', 'punto'],
      ['Arrastrar', 'zona'],
      ['⇧ Arrastrar', 'flecha'],
    ] as [string, string][],
    zoomOut: 'Alejar',
    zoomIn: 'Acercar',
    screenTitle: (index: number, points: number) => `Pantalla ${index} · ${plural(points, 'punto', 'puntos')}`,
    docLabel: (format: string, page: number, sheet?: string, range?: string) =>
      format === 'xlsx' ? `${sheet} ${range}` : `${format === 'pptx' ? 'Diapositiva' : 'Página'} ${page}`,
    pageTitle: (label: string, points: number) => `${label} · ${plural(points, 'punto', 'puntos')}`,
    previous: 'Captura anterior',
    next: 'Captura siguiente',
    noPoints: 'Haz clic en la captura para colocar un punto.',
    undoAll: (mod: string) => `${mod}Z lo deshace todo, incluso un borrado`,
    panel: 'Puntos y notas',
    pointsTab: 'Puntos',
    notes: 'Notas generales',
    note: 'Nota',
    addNote: 'Añadir una nota',
    notesHint: 'sin un punto concreto',
    notePlaceholder: 'Tu nota…',
    dictateNote: 'Seguir dictando',
    dictateMore: (mod: string) => `Seguir dictando (${mod}M)`,
    keyDictate: (mod: string) => [`${mod}M`, 'sigue dictando'] as [string, string],
    stopDictation: 'Detener el dictado',
    deleteNote: 'Eliminar la nota',
    kinds: { point: 'Punto', zone: 'Zona', arrow: 'Flecha' },
    dictated: 'Dictado',
    typed: 'Escrito',
    transcribing: 'transcribiendo…',
    transcriptionError: 'Error de transcripción',
    retry: 'Reintentar',
    recording: 'Dictado en curso',
    tabletDraws: 'la tableta dibuja para este punto',
    sketches: (n: number) => `${plural(n, 'boceto', 'bocetos')} · tableta`,
    zoomSketch: 'Ampliar el boceto',
    deleteSketch: 'Eliminar el boceto',
    inspiration: 'Inspiración',
    inspirationTitle: (shortcut: string, mod: string) =>
      `Adjuntar el ejemplo de otra web: el editor se oculta; abre la página de referencia y pulsa ${shortcut}. O pega una imagen (${mod}V).`,
    inspirationHint: (shortcut: string, mod: string) => `luego ${shortcut} en la página de referencia, o ${mod}V`,
    inspirations: (n: number) => plural(n, 'inspiración', 'inspiraciones'),
    zoomInspiration: 'Ampliar la inspiración',
    deleteInspiration: 'Eliminar la inspiración',
    imageNeedsPoint: 'Selecciona primero un punto: la imagen será su inspiración.',
    unreadableImage: 'Imagen ilegible.',
    deletePoint: 'Eliminar el punto',
    noComment: 'Sin comentario',
    bubbleLabel: (n: number) => `Comentario del punto ${n}`,
    placeholderRecording: 'Habla, o teclea para escribir…',
    placeholder: 'Tu comentario…',
    sketchHint: 'Boceto: dibuja en la tableta',
    keys: [
      ['Intro', 'confirma'],
      ['Esc', 'cancela'],
    ] as [string, string][],
    keyToType: ['cualquier tecla', 'pasa al teclado'] as [string, string],
    thumb: (index: number, first?: number, last?: number) =>
      `Pantalla ${index} · ${first === undefined ? 'sin puntos' : first === last ? `#${first}` : `#${first}–${last}`}`,
    thumbLabel: (index: number, points: number, current: boolean) =>
      `Pantalla ${index}, ${plural(points, 'punto', 'puntos')}${current ? ', mostrada' : ''}`,
    pageThumb: (label: string, first?: number, last?: number) =>
      `${label} · ${first === undefined ? 'sin puntos' : first === last ? `#${first}` : `#${first}–${last}`}`,
    pageThumbLabel: (label: string, points: number, current: boolean) =>
      `${label}, ${plural(points, 'punto', 'puntos')}${current ? ', mostrada' : ''}`,
    captures: 'Capturas de la sesión',
    deleteScreen: (index: number) => `Eliminar la pantalla ${index} y sus puntos`,
    screenDeleted: (index: number, mod: string) => `Pantalla ${index} eliminada · ${mod}Z para deshacer`,
    newCapture: 'Nueva captura',
    emptyTitle: 'Aún no hay capturas',
    emptyBefore: 'En la pantalla que quieres revisar, pulsa',
    emptyAfter: 'y haz clic en el elemento que hay que corregir.',
    emptyVideoBefore: 'Para un vídeo, pulsa',
    emptyVideoAfter: `y navega: ${isMac ? '⌘' : 'Ctrl'} + clic en un elemento seguido de voz se convierte en un punto.`,
    openDocument: 'Comentar un documento',
    emptyDocument: 'Para comentar un PDF, un Word, un Excel o un PowerPoint, suéltalo en esta ventana.',
    opening: (name: string, done: number, total: number) => `${name}: página ${done} / ${total}`,
    micError: (err: unknown) => `Micro no disponible: ${err}`,
    zoomedImage: 'Imagen ampliada',
  },

  main: {
    windows: { pairing: 'Vincular una tableta', settings: 'Ajustes de VibeScreener', welcome: 'Te damos la bienvenida a VibeScreener' },
    newReview: 'Nueva revisión',
    cancel: 'Cancelar',
    nothingToExport: 'Nada que exportar: no hay capturas.',
    nothingToExportDocument: 'Nada que exportar: no hay puntos en el documento.',
    untranscribed: 'Algunos dictados aún no están transcritos.',
    untranscribedPending: (list: string) => `En curso: ${list}`,
    untranscribedError: (list: string) => `Con error: ${list}`,
    exportAnyway: 'Exportar de todos modos',
    exportCancelled: 'Exportación cancelada.',
    note: (n: number) => `nota ${n}`,
    update: (version: string) => `La versión ${version} de VibeScreener está disponible.`,
    updateDetail: (terminal: string) => `Para instalarla, pega este comando en ${terminal}: cierra VibeScreener, la actualiza y la vuelve a abrir. Se conservan las sesiones y los ajustes.`,
    updateDetailMac: 'Como la app no está firmada por Apple, macOS volverá a pedir permiso para la grabación de pantalla, el micro y la accesibilidad (modo vídeo).',
    copyCommand: 'Copiar el comando',
    updateDone: (version: string) => `VibeScreener está actualizada: versión ${version}.`,
    updateIncomplete: (version: string) => `La actualización a la versión ${version} no se completó.`,
    updateIncompleteDetail: (current: string) =>
      `VibeScreener sigue en la versión ${current}. El registro de la instalación explica por qué. Vuelve a intentarlo desde el menú del icono o con el comando de instalación del sitio web.`,
    openLog: 'Abrir el registro',
    close: 'Cerrar',
    shortcutTaken: (label: string) => `${label} ya lo usa otra aplicación.`,
    shortcutTakenAtStart: (label: string) => `El atajo ${label} ya lo usa otra aplicación.`,
    shortcutTakenDetail: 'Elige otro en los ajustes. Puedes seguir capturando desde el icono de VibeScreener.',
    trash: (name: string) => `¿Mover la sesión «${name}» a la papelera?`,
    trashDetail: 'Sus capturas y comentarios se van con ella. Podrás recuperarla desde la papelera.',
    trashConfirm: 'Mover a la papelera',
    trashFailed: (err: string) => `No se ha podido mover a la papelera: ${err}`,
    mcpPortTaken: (port: number) => `El puerto ${port} ya está en uso (¿otra copia de VibeScreener?): Claude Code no puede conectarse.`,
    mcpUnavailable: (err: string) => `Servidor para Claude Code no disponible: ${err}`,
    captureDenied:
      'No se puede capturar: permite la grabación de pantalla (Ajustes del Sistema > Privacidad y seguridad) y reinicia VibeScreener.',
    captureFailed: 'No se puede capturar: no se ha podido leer la pantalla.',
    // Documentos abiertos en la app
    document: {
      filter: 'Documentos',
      legacy: (name: string) => `${name} tiene un formato antiguo de Office: guárdalo como .docx, .xlsx o .pptx, o como PDF.`,
      unsupported: (name: string) =>
        `${name}: formato no compatible. VibeScreener abre PDF, Word (.docx), Excel (.xlsx) y PowerPoint (.pptx).`,
      empty: (name: string) => `${name} no tiene ninguna página que mostrar (hojas ocultas o vacías).`,
      busy: 'Ya se está abriendo un documento.',
      encrypted: 'Este documento está protegido con contraseña: guarda una copia sin protección para comentarlo.',
      unreadable: (err: string) => `No se puede leer el documento: ${err}`,
      truncated: (max: number) => `Documento largo: solo se abren las ${max} primeras páginas.`,
      protectedPdf: (name: string) => `${name} está protegido contra modificaciones: no se puede crear la copia comentada. Las exportaciones para la IA siguen disponibles.`,
      nothingToWrite: 'No hay puntos en ningún documento: nada que escribir en una copia comentada.',
    },
    video: {
      clicks: 'El modo vídeo necesita ver tus clics.',
      clicksDetail: (shortcut: string) =>
        `Autoriza VibeScreener en Ajustes del Sistema > Privacidad y seguridad > Accesibilidad y vuelve a iniciar la grabación (${shortcut}).`,
      openSettings: 'Abrir Ajustes',
      empty: 'No se ha guardado ningún punto.',
      emptyDetail: `Durante la grabación, haz ${isMac ? '⌘' : 'Ctrl'} + clic en un elemento y luego habla: cada punto dictado se conserva. Un clic solo sirve para navegar.`,
      shortcutTaken: (label: string) => `Otra aplicación ya usa el atajo ${label} del modo vídeo.`,
      shortcutTakenDetail: 'El modo vídeo sigue disponible desde el icono de VibeScreener.',
      denied: 'No se puede grabar: autoriza la grabación de pantalla (Ajustes del Sistema > Privacidad y seguridad) y vuelve a abrir VibeScreener.',
      unreadable: 'No se puede grabar: no se ha podido leer la pantalla.',
      noResponse: 'las pantallas o el micro no responden.',
      failed: (err: string) => `No se puede grabar: ${err}`,
    },
    tray: {
      session: (name: string, points: number) => `VibeScreener — ${name} (${plural(points, 'punto', 'puntos')})`,
      recording: 'dictado en curso',
      pending: (n: number) => `${plural(n, 'transcripción', 'transcripciones')} en curso`,
      errors: (n: number) => `${plural(n, 'transcripción', 'transcripciones')} con error`,
      tablet: 'tableta conectada',
    },
    appMenu: {
      about: 'Acerca de VibeScreener',
      settings: 'Ajustes…',
      hide: 'Ocultar VibeScreener',
      quit: 'Salir de VibeScreener',
      edit: 'Edición',
      undo: 'Deshacer',
      redo: 'Rehacer',
      cut: 'Cortar',
      copy: 'Copiar',
      paste: 'Pegar',
      selectAll: 'Seleccionar todo',
      window: 'Ventana',
      minimize: 'Minimizar',
      close: 'Cerrar',
    },
    license: {
      emptyKey: 'Pega la clave que recibiste por correo.',
      notForSale: 'Las licencias aún no están a la venta: vuelve a intentarlo pronto.',
      offline: 'No se puede contactar con Polar: comprueba la conexión a Internet.',
      unknownKey: 'Clave desconocida: compruébala en el correo que recibiste tras la compra.',
      refused: `Clave rechazada: ya activada en el número máximo de ${isMac ? 'Mac' : 'ordenadores'}, revocada o caducada.`,
      polarError: (status: number) => `Polar no responde correctamente (error ${status}): vuelve a intentarlo más tarde.`,
    },
    whisper: {
      modelMissing: 'Falta el modelo de Whisper: descárgalo en los ajustes.',
      binMissing: 'No se encuentra whisper-server.',
      unavailable: (status: string) => `Transcripción no disponible: ${status}`,
      download: (status: number, url: string) => `No se ha podido descargar (${status}): ${url}`,
      stopped: (stderr: string) => `whisper-server se ha detenido al arrancar:\n${stderr}`,
      timeout: 'whisper-server no responde tras 120 s',
      stalled: (url: string) => `Descarga interrumpida (nada recibido en 60 s): ${url}`,
    },
  },

  exports: {
    colon: ': ',
    date: (iso: string) => longDate('es-ES', iso),
    reviewFile: 'revision',
    partFile: (i: number, n: number) => `parte-${i}-de-${n}`,
    part: (i: number, n: number) => `parte ${i}/${n}`,
    partScreens: (first: number, last: number) => `esta parte: pantallas ${first} a ${last}`,
    screen: (n: number) => `Pantalla ${n}`,
    position: 'Posición',
    point: (x: number, y: number, size: string) => `x ${x}, y ${y} ${size}`,
    zone: (x: number, y: number, w: number, h: number, size: string) => `zona x ${x}, y ${y}, ${w} × ${h} ${size}`,
    arrow: (x1: number, y1: number, x2: number, y2: number, size: string) => `flecha de (${x1}, ${y1}) a (${x2}, ${y2}) ${size}`,
    on: (w: number, h: number) => `sobre ${w} × ${h}`,
    page: (page: number, pages: number, name: string) => `Página ${page} / ${pages} — ${name}`,
    slide: (page: number, pages: number, name: string) => `Diapositiva ${page} / ${pages} — ${name}`,
    sheet: (sheet: string, range: string, name: string) => `Hoja ${sheet} (${range}) — ${name}`,
    anchorCells: (cells: string, sheet: string, value?: string) => `celda ${cells} de la hoja ${sheet}${value ? ` («${value}»)` : ''}`,
    anchor: (text: string) => `texto señalado: «${text}»`,
    commented: (i: number) => (i > 1 ? `comentado ${i}` : 'comentado'),
    sketchCount: (n: number) => plural(n, 'boceto', 'bocetos'),
    inspirationCount: (n: number) => plural(n, 'inspiración', 'inspiraciones'),
    seeExport: (list: string) => `${list} en la exportación de VibeScreener`,
    yes: 'sí',
    no: 'no',
    context: 'Contexto',
    instructions: 'Instrucciones',
    notes: 'Notas generales',
    summary: 'Resumen',
    columns: { screen: 'Pantalla', comment: 'Comentario', sketch: 'Boceto', inspiration: 'Inspiración' },
    noComment: '(sin comentario)',
    zoomOn: (n: number) => `Zoom en #${n}`,
    sketchOf,
    inspiration: 'Inspiración',
    inspirationOf,
    inspirationNote,
  },

  mcp: {
    instructions: `VibeScreener guarda revisiones de interfaz: capturas de pantalla en las que cada observación es un punto numerado (#1 a #N) con un comentario, a menudo dictado, y a veces un boceto o una inspiración (captura de otra web que muestra el resultado deseado, no la pantalla que hay que modificar).
Para aplicar una revisión al código: si el usuario no indica otra cosa, usar la sesión abierta en VibeScreener (opción por defecto); si no, elegirla con lister_sessions. lire_revue da todas las observaciones; voir_ecran muestra, pantalla por pantalla, la captura anotada, un zoom alrededor de cada punto, los bocetos y las inspiraciones. Mirar cada pantalla antes de modificar el código. Si una observación es ambigua, hacer una pregunta en lugar de adivinar.`,
    sessionParam: 'Id de la sesión (ver lister_sessions). Por defecto: la sesión abierta en VibeScreener o, si no hay ninguna, la más reciente.',
    listTool: 'Lista las sesiones de revisión recientes (nombre, fecha, número de puntos, id), de la más reciente a la más antigua.',
    reviewTool:
      'Todas las observaciones de una sesión, en texto: contexto, instrucciones y luego cada punto (número, pantalla, comentario, posición, bocetos, inspiraciones). Las imágenes se obtienen con voir_ecran.',
    screenTool:
      'Una pantalla de una sesión: la captura con sus puntos numerados y, para cada punto, su comentario, un zoom alrededor del elemento señalado, sus bocetos y sus inspiraciones (capturas de otras webs, modelos del resultado deseado).',
    screenParam: 'Número de la pantalla, de 1 al número de pantallas que indica lire_revue.',
    noSession: 'No hay ninguna sesión: hacer primero una captura con VibeScreener.',
    notFound: (id: string) => `Sesión «${id}» no encontrada.`,
    notFoundList: (id: string) => `Sesión «${id}» no encontrada: ver lister_sessions.`,
    noSessions: 'Aún no hay ninguna sesión.',
    sessions: 'Sesiones, de la más reciente a la más antigua:',
    sessionLine: (name: string, date: string, points: number, id: string, open: boolean) =>
      `- ${name} · modificada el ${date} · ${plural(points, 'punto', 'puntos')} · id: ${id}${open ? ' (abierta en VibeScreener)' : ''}`,
    untranscribed: (list: string) => `Atención: dictado aún no transcrito para ${list}; el comentario puede estar incompleto.`,
    noPoints: '(sin puntos)',
    sketches: (n: number) => plural(n, 'boceto', 'bocetos'),
    inspirations: (n: number) => plural(n, 'inspiración', 'inspiraciones'),
    seeScreens: (n: number) =>
      `Para ver la captura anotada, el zoom de cada punto, los bocetos y las inspiraciones: voir_ecran con ecran de 1 a ${n}.`,
    seeScreensList: (list: string) =>
      `Se omiten las páginas sin puntos. Para ver cada página comentada (captura anotada, zoom de cada punto, bocetos, inspiraciones): voir_ecran con ecran = ${list}.`,
    noScreen: (screen: string, name: string, screens: number) =>
      `La pantalla ${screen} no existe: la sesión «${name}» tiene ${plural(screens, 'pantalla', 'pantallas')}.`,
    zoom: 'Zoom en el elemento señalado:',
    error: (err: string) => `Error de VibeScreener: ${err}`,
  },

  glossary:
    'Revisión de interfaz: botón, border-radius de 8 px, padding, margin, header, footer, ' +
    'sidebar, navbar, modal, dropdown, hover, focus, flexbox, grid, z-index, opacidad.',

  instructions: `Este documento enumera {N} observaciones sobre una interfaz, numeradas de #1 a #{N}.
Cada observación señala un elemento en una captura de pantalla: el marcador numerado y el
recorte muestran el elemento en cuestión, un rectángulo indica una zona y una flecha, un desplazamiento.
Aplica cada observación en el código. Si alguna es ambigua, haz una pregunta en lugar
de adivinar. Al final, enumera los números que has aplicado y los que no.`,

  /** Instrucciones por defecto de una sesión hecha de páginas de documento. */
  instructionsDocument: `Esta revisión enumera {N} observaciones sobre un documento, numeradas de #1 a #{N}.
Cada observación señala un lugar de una página: el marcador numerado y el recorte muestran
el pasaje en cuestión, citado cuando es posible («texto señalado»), un rectángulo indica una zona
y una flecha, un desplazamiento. Aplica cada observación al documento. Si alguna es ambigua,
haz una pregunta en lugar de adivinar. Al final, enumera los números que has aplicado y los que no.`,

  sessionName: (d: Date) => `Revisión ${isoDay(d)} ${hhmm(d, ':')}`,
};
