// Textes de la PWA, regroupés pour une traduction future.

export const T = {
  labels: {
    toolbar: 'Outils de dessin',
    pen: 'Stylo',
    eraser: 'Gomme',
    '#1D1D1F': 'Noir',
    '#E5341F': 'Rouge',
    '#2563EB': 'Bleu',
    '4': 'Trait fin',
    '10': 'Trait épais',
    undo: 'Annuler',
    clear: 'Effacer la toile',
  } as Record<string, string>,
  backgrounds: { blanc: 'Fond blanc', quadrillé: 'Fond quadrillé', recadrage: 'Fond : capture' },
  connected: "Connectée à l'ordinateur",
  offline: 'Hors connexion',
  offlineBanner: 'Pas de réseau : le dessin reste ici, envoyez-le au retour du réseau.',
  notPaired: 'Tablette non appairée',
  notPairedHint: "Scannez le code QR affiché par VibeScreener sur l'ordinateur.",
  waiting: 'VibeScreener',
  waitingHint: "En attente de VibeScreener sur l'ordinateur…",
  point: (n: number) => `Point #${n}`,
  noComment: 'Sans commentaire',
  noSelection: 'Aucun point sélectionné',
  noSelectionHint: (n: number) => `L'envoi ira au dernier point, #${n}.`,
  noPoint: "Aucun point sur l'ordinateur",
  noPointHint: "Posez un point sur l'ordinateur pour lui joindre un croquis.",
  send: (n?: number) => (n ? `Envoyer au #${n}` : 'Envoyer'),
  sent: (n: number) => `Joint au point #${n}`,
  notConfirmed: 'Envoi non confirmé, réessayez',
  welcomeTitle: 'Tablette appairée',
  welcomeText: "Installez-la : Partager › Sur l'écran d'accueil. Elle s'ouvrira ensuite sans barre d'adresse.",
  welcomeStart: 'Commencer à dessiner',
};
